d = input()
r = input()
f = open(d, "r+")
data = f.read()

print("=== Before the deletion")
print(data)
data = data.replace(r, "")
print("=== After the deletion")
print(data)
f.seek(0)
f.write(data)
f.close()